# Generated by Django 5.1 on 2024-08-25 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge_base", "0001_initial"),
        ("members", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMemberPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allowed_graphs", models.JSONField(blank=True, null=True)),
                ("allowed_app_actions", models.JSONField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_collection_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permissions",
                        to="knowledge_base.workspacecollectiondocument",
                    ),
                ),
                (
                    "allowed_collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permissions",
                        to="knowledge_base.workspacecollection",
                    ),
                ),
                (
                    "allowed_workflows",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permissions",
                        to="workflows.workspaceworkflow",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_member_permissions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_member_permissions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_member_permissions",
                        to="members.workspacemember",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace_member"], name="idx_ws_mem_perm_ws_mem_id"
                    ),
                    models.Index(fields=["is_active"], name="idx_ws_mem_perm_active"),
                    models.Index(
                        fields=["created_by"], name="idx_ws_mem_perm_created_by"
                    ),
                    models.Index(
                        fields=["updated_by"], name="idx_ws_mem_perm_updated_by"
                    ),
                ],
            },
        ),
    ]
