# Generated by Django 5.1 on 2024-08-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workspacecollectiondocument",
            name="idx_ws_coll_doc_coll_id",
        ),
        migrations.RemoveIndex(
            model_name="workspacecollectiondocument",
            name="idx_ws_coll_doc_created_by",
        ),
        migrations.RemoveIndex(
            model_name="workspacecollectiondocument",
            name="idx_ws_coll_doc_embed",
        ),
        migrations.RemoveIndex(
            model_name="workspacecollectiondocument",
            name="idx_ws_coll_doc_title",
        ),
        migrations.RemoveIndex(
            model_name="workspacecollectiondocument",
            name="idx_ws_coll_doc_updated_by",
        ),
    ]
