# Generated by Django 5.1 on 2024-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge_base",
            "0002_remove_workspacecollectiondocument_idx_ws_coll_doc_coll_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspacecollectiondocument",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="workspacecollectiondocument",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
