# Generated by Django 5.1 on 2024-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge_base",
            "0003_alter_workspacecollectiondocument_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecollection",
            name="workspace_id",
            field=models.CharField(
                default="bee9d121-a53e-418c-9e9b-991bb7b29312", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="workspacecollectiondocument",
            name="workspace_id",
            field=models.CharField(
                default="bee9d121-a53e-418c-9e9b-991bb7b29312", max_length=255
            ),
        ),
    ]
