# Generated by Django 5.1 on 2024-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0004_workspacecollection_workspace_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacecollection",
            name="workspace_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="workspacecollectiondocument",
            name="workspace_id",
            field=models.CharField(max_length=255),
        ),
    ]
