# Generated by Django 5.1 on 2024-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0005_alter_workspacecollection_workspace_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecollectiondocument",
            name="uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
