# Generated by Django 5.1 on 2024-09-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0008_alter_workspacecollection_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspacecollection",
            name="workspace_id",
        ),
        migrations.RemoveField(
            model_name="workspacecollectiondocument",
            name="workspace_id",
        ),
    ]
